---
- name: Installing packages
  yum: 
    name: "{{ item }}"
    state: present
  loop:
    - httpd
    - net-tools
    - wget
- name: starting and enabling httpd services
  service:
    name: httpd
    state: started
    enabled: yes
- name: configuring httpd.conf
  template:
    src: httpd.j2
    dest: /etc/httpd/conf/httpd.conf
    backup: yes
  notify: restart httpd

- name: making index.html
  shell: echo "<h1>Test Page</h1>" > /var/www/html/index.html

- name: opening firewall
  firewalld:
    service: http
    permanent: true
    state: enabled
  notify: restart firewalld
    
- name: running wget
  shell: wget 127.0.0.1 2>&1
  register: wget_output

- name: display wget
  debug:
    msg: "{{ wget_output.stdout }}"

- name: restart
  service:
    name: httpd
    state: restarted

- name: restart
  service:
    name: firewalld
    state: restarted
