---
- name: create a local user with password
  hosts: db
  become: yes
  vars_files:
    - pass.yml
  tasks:
    - name: create a user
      user:
        name: "ansziyo"
        password: "{{ passwd | password_hash('sha512') }}"
        shell: "/bin/bash"
        state: present
