---
- name: Setup Apache Web Server
  hosts: db
  become: yes
  vars:
    package: httpd
 
  tasks:
    - name: uninstalling httpd
      yum:
        name: "{{ package }}"
        state: absent
 
    - name: open firewall port 80 for HTTP
      firewalld:
        port: 80/tcp
        permanent: true
        state: enabled
        immediate: yes
      notify: Restart firewalld

  handlers:
    - name: Restart firewalld
      service:
        name: firewalld
        state: restarted
